[build]
target = "index.html"
dist = "dist"

[[hooks]]
stage = "build"
command = "sh"
command_arguments = ["-c", "./tailwindcss -i src/tailwind.scss -o $TRUNK_STAGING_DIR/tailwind.css"]

[[hooks]]
stage = "pre_build"
command = "./tailwindcss"
command_arguments = ["-i", "./src/tailwind.scss", "-o", "tailwind.scss"]
